
RESIDENTIAL = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[1]/div/button[2]"
COMMERCIAL = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[1]/div/button[1]"
BODY_CORPORATE = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[1]/div/button[3]"
BLOCKED_DRAIN = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[7]/div[1]/button"
WINDOW_BROKEN = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[9]/div[2]/button"
WHERE_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[1]/div[2]/input"
WHERE_2 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[4]/div[1]/div[2]/input"
WHERE_3 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[6]/div[1]/div[2]/input"
PHOTO_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[4]/div/div[1]/input"
PHOTO_2 = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[3]/div[4]/div[4]/div/div[1]/input"
SUBMIT_1 = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[3]/div[8]/button"
SUBMIT_2 = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[3]/div[6]/button"
NOT_LISTED = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/div[2]/button"
ISSUE_ITEM_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[2]/div[1]/input"
DESCRIPTION_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[3]/div[1]/textarea"
ERROR_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[3]/div[2]"
ERROR_2 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[5]/div[5]/div[1]/div"
IRRIGATION = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[2]/div[2]/button"
GARAGE = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[3]/div[1]/button"
OVEN = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[2]/div[1]/button"
TAP = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[5]/div[1]/button"
ROOF = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[9]/div[1]/button"
POPUP = "/html/body/div[2]/p"


