
residential = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[1]/div/button[2]"
commercial = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[1]/div/button[1]"
body_corporate = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[1]/div/button[3]"
blocked_drain = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[7]/div[1]/button"
window_broken = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[9]/div[2]/button"
where_is_your_problem_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[1]/div[2]/input"
where_is_your_problem_2 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[4]/div[1]/div[2]/input"
where_is_your_problem_3 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[6]/div[1]/div[2]/input"
photo_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[4]/div/div[1]/input"
photo_2 = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[3]/div[4]/div[4]/div/div[1]/input"
submit = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[3]/div[8]/button"
submit_2 = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[3]/div[6]/button"
not_listed = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/div[2]/button"
issue_item_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[2]/div[1]/input"
description_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[3]/div[1]/textarea"
error_1 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[2]/div[3]/div[2]"
error_2 = "/html/body/div/div/div/div[1]/div[2]/div[3]/div[3]/div[5]/div[5]/div[1]/div"
irrigation = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[2]/div[2]/button"
garage = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[3]/div[1]/button"
oven = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[2]/div[1]/button"
tap = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[5]/div[1]/button"
roof = "//*[@id='main-wrapper']/div/div/div[1]/div[2]/div[3]/div[2]/ul/li/div[9]/div[1]/button"
popup = "/html/body/div[2]/p"


